import { Inter } from "next/font/google";
import "./ui/globals.css"; // Imported form ./ui/ This is within docs, I know it's weird and doesn't
//follow the proper React file structure, but let's assume this is 100% correct.

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
